<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MeowField.Application\MeowField.Application.csproj" />
    <ProjectReference Include="..\MeowField.Domain\MeowField.Domain.csproj" />
    <ProjectReference Include="..\MeowField.Infrastructure.Midi\MeowField.Infrastructure.Midi.csproj" />
    <ProjectReference Include="..\MeowField.Infrastructure.Windows\MeowField.Infrastructure.Windows.csproj" />
    <ProjectReference Include="..\MeowField.Infrastructure.Storage\MeowField.Infrastructure.Storage.csproj" />
    <ProjectReference Include="..\MeowField.Infrastructure.Audio\MeowField.Infrastructure.Audio.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\MeowField_AutoPiano.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="game_configs\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="MahApps.Metro.IconPacks.Lucide" Version="6.2.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\MeowField_AutoPiano.ico</ApplicationIcon>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <Version>2.2.7</Version>
    <AssemblyName>MeowField_AutoPiano</AssemblyName>
    <StartupObject>MeowField.App.Program</StartupObject>
    <SatelliteResourceLanguages>zh-Hans</SatelliteResourceLanguages>
  </PropertyGroup>
</Project>
